language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: release
  on:
    branch: master

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "jayken"
      - git config --local user.email "jaykenxie@outlook.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist
  skip_cleanup: true
  on:
    branch: master
