language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: release
  on:
    branch: master

before_deploy:
  - git config --local user.name "jaykenxie"
  - git config --local user.email "jaykenxie@outlook.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - sudo apt-get -y install zip
  - zip -r amoz.zip dist/ -r
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - assets.zip
  skip_cleanup: true
  on:
    branch: master
